---
language: ruby
script: "bundle exec ruby test/run.rb"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.1.0
  - jruby
  - ree
  - rbx
  - rbx-2
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: rbx-2
cache: bundler
